<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VNAON2C" failures="0" tests="3" name="com.qa.adminTest.ProductTest" time="0.002" errors="1" timestamp="2024-01-03T15:58:03 IST" skipped="2">
  <testcase classname="com.qa.adminTest.ProductTest" name="beforeCalss" time="0.002">
    <error message="java.util.Random.nextInt(II)I" type="java.lang.NoSuchMethodError">
      <![CDATA[java.lang.NoSuchMethodError: java.util.Random.nextInt(II)I
at com.qa.adminTest.ProductTest.beforeCalss(ProductTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- beforeCalss -->
  <system-out/>
  <testcase classname="com.qa.adminTest.ProductTest" name="addNewProduct" time="0.000">
    <skipped/>
  </testcase> <!-- addNewProduct -->
  <system-out/>
  <testcase classname="com.qa.adminTest.ProductTest" name="addProductUnderCatgory" time="0.000">
    <skipped/>
  </testcase> <!-- addProductUnderCatgory -->
  <system-out/>
</testsuite> <!-- com.qa.adminTest.ProductTest -->
